version: '3'
services:
  db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - '3306:3306'
    expose:
        - '3306'
    volumes:
        - ./mysql:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
